---
token:
  description: "GitHub oAuth Token"
  type: "string"
  default: "{{system.github_oauth_token}}"
  required: true

github_exhange_org:
  type: "string"
  description: "Name of the exchange's GitHub organization"

stackstorm_environment:
  type: "string"
  description: "The environment stackstorm is running in"

skip_dependencies_on_install:
  type: "boolean"
  description: "Set to true to skip dependencies when installing packs via the install action"

github_user:
  type: "string"
  description: "The name of the github user"

github_token:
  type: "string"
  description: "The token for the given github_user"