---
token:
  description: "GitHub oAuth Token"
  type: "string"
  default: "{{system.github_oauth_token}}"
  required: true

github_exhange_org:
  type: "string"
  description: "The url to the github org that is hosting an exchange"

stackstorm_environment:
  type: "string"
  description: "The environment stackstorm is running in"